### ISSUE TITLE
Sir I am not able to run my script. I have also changed the permissions of files but still not working.

### ISSUE THREAD

**Issue by Hitechverma** [geduldig/TwitterAPI#51]
Traceback (most recent call last):
  File "tweet.py", line 1, in <module>
    from TwitterAPI import TwitterAPI
  File "/usr/lib/python2.7/dist-packages/TwitterAPI/TwitterAPI.py", line 9, in <module>
    from requests.exceptions import ConnectionError, ReadTimeout, SSLError
ImportError: cannot import name ReadTimeout

**Comment by geduldig** [comment]
You probably need to upgrade your requests library.
