### ISSUE TITLE
import TwitterAPI exception

### ISSUE THREAD

**Issue by k0a1a** [geduldig/TwitterAPI#61]
hitting this error:

```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from TwitterAPI import TwitterAPI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/TwitterAPI/TwitterAPI.py", line 10, in <module>
    from requests.packages.urllib3.exceptions import ReadTimeoutError, ProtocolError
ImportError: cannot import name ReadTimeoutError
>>> import TwitterAPI
>>> TwitterAPI.__version__
'2.3.3.1'
>>> 
>>> import urllib3
>>> urllib3.__version__
'1.9.1'
>>> 
```

TwitterAPI is installed via pip

**Comment by geduldig** [comment]
Most likely you have an older requests lib. Try `pip install TwitterAPI --upgrade` to get the latest of everything, or `pip install requests --upgrade` to get just the latest `requests`. If you don't use pip or easy_install, you will have to manually upgrade.

**Comment by k0a1a** [comment]
```pip install TwitterAPI --upgrade``` did it, many thanks
